  function displayArticle1() {
  document.getElementById("a_title").innerHTML = ""
  document.getElementById("a_paragraph").innerHTML = "  <div class='bolg_all_paragraph' id='lake_paragraph'><div class='wrapper itemawrapper'><div class='item ia' id='ia'><p class='date'>30 . 03 . 2020</p><p class='straitline'>|</p><p class='weather'>Sunny</p></div></div><div class='wrapper itembwrapper'><div class='item ib'><img src='../docs/myart/IMG_0004.JPG' alt='cats' class='art1' id='art1'></div></div><div class='wrapper itemcwrapper'><div class='item ic'><img src='../docs/myart/IMG_0124.JPG' alt='Rabbits' class='art2' id='art2'></div></div><div class='wrapper itemdwrapper'><div class='item id' id='id'><p class='textd' id='textd'>Lake is my favourite coloring app for iPad. It has a large collection of coloring books by indie illustrators. If you are seeking to relax through creativity, lake is the perfect app for you.</p></div></div></div>"
}

function displayArticle2() {
  document.getElementById("a_title").innerHTML = ""
  document.getElementById("a_paragraph").innerHTML = "<div class='bolg_all_paragraph' id='procreate_paragraph'><div class='wrapper itemawrapper'><div class='item ia' id='ia'><p class='date'>05 . 03 . 2020</p><p class='straitline'>|</p><p class='weather'>Cloudy</p></div></div><div class='wrapper itembwrapper'><div class='item ib'><img src='../docs/plants/bluebeans.png' alt='plants' class='plants' id='plants'></div></div><div class='wrapper itemcwrapper'><div class='item ic'><p class='textc' id='textd'>When visiting a plant nursery, are you often attracted by succulents and cacti growing in the flower pots? They come in a variety of shapes, sizes, colors, and textures. It is easy to find a plant that will fit any style. What should novices pay attention to when growing succulents? I have summarised some of the things that I have learned during my own experience of planting succulents, hoping to help people who are also interested in succulents. </p></div></div><div class='wrapper itemdwrapper'><div class='item id' id='id'><p class='textd' id='textd'>I think it is particularly important to note one thing: Don't water your succulents too often! Succulents are originated from dry, deserted areas (such as Africa), and they can store water in their thick leaves for survival. You may kill your succulents from too much water.  When roots stay wet for a long time, either because you water too frequently or the soil doesn’t dry out fast enough, the roots don’t get enough air and so they'll become rotted. In this case, leaves will turn yellow and fall off.</p></div></div></div>"
}
function displayArticle3() {
  document.getElementById("a_title").innerHTML = ""
  document.getElementById("a_paragraph").innerHTML = " <div class='bolg_all_paragraph' id='procreate_paragraph'><div class='wrapper itemawrapper'><div class='item ia' id='ia'><p class='date'>23 . 02 . 2020</p><p class='straitline'>|</p><p class='weather'>Cloudy</p></div></div><div class='wrapper itembwrapper'><div class='item ib'><img src='../docs/myart/IMG_0120.PNG' alt='portrait' class='portrait' id='portrait'></div></div><div class='wrapper itemcwrapper'><div class='item ic'><img src='../docs/myart/IMG_0142.PNG' alt='Rabbits' class='cat' id='cat'></div></div><div class='wrapper itemdwrapper'><div class='item id' id='id'><p class='textd' id='textd'>Procreate is currently the most popular ipad painting software among professional artists.<br><br>You can create high level professional quality illustrations with this software. You can customize the brush in it to get the texture of a variety of different paint strokes, you can also directly import the color palette downloaded from the internet, so even if you are a drawing beginner, you can still create a stunning artwork.</p></div></div></div>"
}

function displayArticle4() {
  document.getElementById("a_title").innerHTML = ""
  document.getElementById("a_paragraph").innerHTML = "<div class='bolg_all_paragraph' id='procreate_paragraph'><div class='wrapper itemawrapper'><div class='item ia' id='ia'><p class='date'>20 . 02 . 2020</p><p class='straitline'>|</p><p class='weather'>Windy</p></div></div><div class='wrapper itembwrapper'><div class='item ib'><img src='../docs/undraw_book_reading_kx9s.svg' alt='plants' class='plants'></div></div><div class='wrapper itemcwrapper'><div class='item ic'><p class='textc' id='textd'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, id cum asperiores magni dolore voluptatum et eaque! Aut, aperiam in deserunt vero fuga quam iure facilis laborum.<br><br> Perferendis voluptatibus quaerat nostrum inventore. Perferendis voluptatibus quaerat nostrum inventore? Cumque exercitationem voluptas atque ipsam nobis possimus impedit? </p></div></div><div class='wrapper itemdwrapper'><div class='item id' id='id'><p class='textd' id='textd'>Aut, aperiam in deserunt vero fuga quam iure facilis laborum. Perferendis voluptatibus quaerat nostrum inventore. <br><br>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, id cum asperiores magni dolore voluptatum et eaque! Aut, aperiam in deserunt vero fuga quam iure facilis laborum. Aut, aperiam in deserunt vero fuga quam iure facilis laborum. Perferendis voluptatibus quaerat nostrum inventore.</p></div></div></div>"
}

function displayArticle5() {
  document.getElementById("a_title").innerHTML = ""
  document.getElementById("a_paragraph").innerHTML = " <div class='bolg_all_paragraph' id='procreate_paragraph'><div class='wrapper itemawrapper'><div class='item ia' id='ia'><p class='date'>15 . 02 . 2020</p><p class='straitline'>|</p><p class='weather'>Sunny</p></div></div><div class='wrapper itembwrapper'><div class='item ib'><img src='../docs/brekfast/IMG_3519.JPG' alt='breakfast1' class='arvo_sandwitch' id='arvo_sandwitch'></div></div><div class='wrapper itemcwrapper'><div class='item ic'><img src='../docs/brekfast/IMG_3826.jpg' alt='Breakfast2' class='cat' id='cat'></div></div><div class='wrapper itemdwrapper'><div class='item id' id='id'><p class='textd' id='textd'>‘Breakfast is the most important meal of the day!’<br><br> I agree! For me, colourful, delicious breakfast will brighten up my life! Breakfast also plays an important role in my performances throughout the day. This is why I like to cook breakfast.<br><br>What do you usually have for breakfast?</p></div></div></div>"
}

function displaywelcome() {
  document.getElementById("a_title").innerHTML = " "
  document.getElementById("a_paragraph").innerHTML = " <div class='welcome_paragraph'><p class='welcome'>Welcome to my blog!</p><img src='../docs/undraw_making_art_759c.svg' alt='making art'><p class='select_left'>⬅&nbsp;&nbsp; Read more...</p></div>"
}